# PR에 자동으로 reviewer를 추가할지 여부
addReviewers: true

# PR에 자동으로 assignee를 추가할지 여부
addAssignees: true

# 자동으로 리뷰어로 등록될 수 있는 GitHub 계정 목록(GitHub user name)
reviewers:
  - Byeongsu-cmd
  - cjn404
  - zerone1202
  - AllSungho
  - assokk

# PR 제목에 특정 키워드가 포함되면 자동 reviewer 추가를 건너뜀
skipKeywords:
  - skip

# 랜덤으로 추가할 reviewer의 수
# 0이면 reviewers 목록의 모든 사람을 추가
numberOfReviewers: 1